import type { Metadata } from "next";
import localFont from "next/font/local";
import { Inter } from 'next/font/google';
import "./globals.css";

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}  antialiased`}>
        <div
          className="fixed inset-0 overflow-auto"
          style={{
            background: `
              linear-gradient(
                to bottom,
                rgba(128, 0, 128, 0.3) 0%,
                rgba(128, 0, 128, 0.2) 40%,
                rgba(128, 0, 128, 0.1) 70%,
                rgba(128, 0, 128, 0.05) 85%,
                transparent 100%
              ),
              linear-gradient(to bottom, #050505, #050505)
            `,
          }}
        />
        <div className="relative min-h-screen">{children}</div>
      </body>
    </html>
  );
}

